// docs/snippets/svelte/src/Pages/Home.svelte
<script lang="ts">
  import { Deferred } from '@inertiajs/svelte'

  type Stats = {
    projects: number
    tasks: number
  }

  let {
    greeting = 'Hello',
    stats,
  }: {
    greeting?: string
    stats?: Stats
  } = $props()
</script>

<main>
  <h1>{greeting} from inertia-axum</h1>

  <Deferred data="stats">
    {#snippet fallback()}
      <p>Loading stats…</p>
    {/snippet}

    {#if stats}
      <p>{stats.projects} projects · {stats.tasks} tasks</p>
    {/if}
  </Deferred>
</main>

// docs/snippets/vue/src/Pages/Home.vue
<script setup lang="ts">
import { Deferred } from '@inertiajs/vue3'

const props = withDefaults(
  defineProps<{
    greeting?: string
    stats?: {
      projects: number
      tasks: number
    }
  }>(),
  {
    greeting: 'Hello',
  },
)
</script>

<template>
  <main>
    <h1>{{ props.greeting }} from inertia-axum</h1>

    <Deferred data="stats">
      <template #fallback>
        <p>Loading stats…</p>
      </template>

      <p v-if="props.stats">
        {{ props.stats.projects }} projects ·
        {{ props.stats.tasks }} tasks
      </p>
    </Deferred>
  </main>
</template>
