// docs/snippets/svelte/src/Pages/Home.svelte
<script lang="ts">
  import { Deferred } from '@inertiajs/svelte'

  type Stats = {
    projects: number
    tasks: number
  }

  let {
    greeting = 'Hello',
    stats,
  }: {
    greeting?: string
    stats?: Stats
  } = $props()
</script>

<main>
  <h1>{greeting} from inertia-axum</h1>

  <Deferred data="stats">
    {#snippet fallback()}
      <p>Loading stats…</p>
    {/snippet}

    {#if stats}
      <p>{stats.projects} projects · {stats.tasks} tasks</p>
    {/if}
  </Deferred>
</main>

// docs/snippets/react/src/Pages/Home.tsx
import { Deferred } from '@inertiajs/react'

type Props = {
  greeting?: string
  stats?: {
    projects: number
    tasks: number
  }
}

export default function Home({ greeting = 'Hello', stats }: Props) {
  return (
    <main>
      <h1>{greeting} from inertia-axum</h1>

      <Deferred data="stats" fallback={<p>Loading stats…</p>}>
        {stats && (
          <p>
            {stats.projects} projects · {stats.tasks} tasks
          </p>
        )}
      </Deferred>
    </main>
  )
}
